name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - run: ./gradlew package
        shell: bash
      - run: find build
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          path: build/compose/binaries/main/**/*untitled2-1.0.*
